repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: [--config=ruff.toml, --statistics, --fix]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
        exclude: >
          (?x)^(
              .github/repo_meta.yaml|
              .*recipe/meta.yaml|
          )$

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=90]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.9.1
    hooks:
      - id: commitizen

  - repo: local
    hooks:
      - id: set-permissions
        name: Set script permissions
        entry: chmod +x ./.github/scripts/check_readme.py
        language: system
        pass_filenames: false
        always_run: true
