name: Auto PR Bot

on:
  issues:
    types: [opened, reopened]

jobs:
  respond:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Google Gemini SDK
      run: pip install google-generativeai

    - name: Install dependencies
      run: pip install -r .github/agent/requirements.txt

   
    - name: List available models
      id: list_models
      run: |
        python .github/agent/list_models.py
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPO: ${{ github.repository }}
      shell: bash     
    - name: Run the Agent
      run: |
        python .github/agent/auto_pr_bot.py
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPO: ${{ github.repository }}
      shell: bash  
