name: Python Package CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip list

      - name: Build package
        run: |
          hatch build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: py-artifacts
          path: dist/*

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: py-artifacts
          path: ./py-artifacts

      - name: Install package from artifact
        run: |
          cd ./py-artifacts && ls -la
          pip install *.whl

  validate:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Get package Info
        run: |
          pip show my-hw
          hello-world
