name: PR Draft

on:
  pull_request:
    types:
      [
        edited,
        opened,
        reopened,
        synchronize,
        converted_to_draft,
        ready_for_review,
      ]

permissions:
  contents: read
  pull-requests: write
jobs:
  add-label-draft:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add label to draft PR
        uses: actions-ecosystem/action-add-labels@bd52874380e3909a1ac983768df6976535ece7f8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: DO NOT MERGE
  remove-label-draft:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove label from PR
        uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: DO NOT MERGE
