name: Python Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test Env ${{ matrix.download_name }}-${{ matrix.python-version}}
    runs-on: ${{ matrix.os }}
    env:
        TERM: unknown
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_AUTHENTICATOR: SNOWFLAKE_JWT
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_CONNECTIONS_MYCONNECTION_PRIVATE_KEY_RAW: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_RAW }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Ubuntu
          - os: ubuntu-latest
            python-version: "3.9"
            cloud-provider: aws
            snow_cli_version: "2.8.2"
            download_name: linux
          - os: ubuntu-latest
            python-version: "3.10"
            cloud-provider: aws
            snow_cli_version: "3.2.0"
            download_name: linux
          - os: ubuntu-latest
            python-version: "3.11"
            cloud-provider: aws
            snow_cli_version: "3.2.0"
            download_name: linux
          - os: ubuntu-latest
            python-version: "3.12"
            cloud-provider: aws
            snow_cli_version: "3.2.0"
            download_name: linux 

          # Windows
          - os: windows-latest
            python-version: "3.10"
            cloud-provider: aws
            snow_cli_version: "2.8.2"
            download_name: windows  
          - os: windows-latest
            python-version: "3.10"
            cloud-provider: aws
            snow_cli_version: "3.1.0"
            download_name: windows
          - os: windows-latest
            python-version: "3.11"
            cloud-provider: aws
            snow_cli_version: "3.1.0"
            download_name: windows  
          
          # macOS  
          - os: macos-latest
            python-version: "3.11"
            cloud-provider: aws
            snow_cli_version: "3.2.0"
            download_name: macos   

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Print Current Python Env
        run: |
          python --version && pip --version

      - name: Set up Snowflake CLI
        uses: Snowflake-Labs/snowflake-cli-action@v1.5
        with:
          cli-version: ${{ matrix.snow_cli_version }}
          default-config-file-path: ".github/workflows/config/config.toml"

      - name: Execute Snowflake CLI
        run: |
          snow --info   
          snow --version

      - name: Test Snowflake CLI
        run: |
          snow connection list
          snow connection test -c myconnection --debug
          snow connection test -c myconnection | grep Status

