name: Hadoop on Windows

on:
  push:
    branches:
      - main

jobs:
  setup-hadoop:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11' # Hadoop supports Java 8 or 11
        distribution: 'temurin'

    - name: Download Hadoop
      run: |
        curl -O https://dlcdn.apache.org/hadoop/common/hadoop-3.3.6/hadoop-3.3.6.tar.gz
        tar -xvf hadoop-3.3.6.tar.gz
        move hadoop-3.3.6 hadoop

    - name: Setup Hadoop Environment
      run: |
        echo "## Configuring Hadoop Environment"
        $env:HADOOP_HOME = "${{ github.workspace }}\hadoop"
        $env:PATH += ";$env:HADOOP_HOME\bin"
        Write-Output "HADOOP_HOME is $env:HADOOP_HOME"

    - name: Verify HADOOP_HOME
      run: |
        echo "Verifying HADOOP_HOME"
        echo HADOOP_HOME is $env
