name: Generate Timestamp Workflow

on:
  push:
    branches:
      - main

jobs:
  generate-timestamp_v2:
    runs-on: ubuntu-latest
    steps:
      - name: Generate timestamp
        run: |
          echo "timestamp=$(date +%Y%m%d%H%M%S%3N)" >> $GITHUB_ENV

      - name: Use timestamp
        run: |
          echo "El timestamp generado es: ${{ env.timestamp }}"

      - name: Create file with timestamp
        run: echo "Este archivo fue generado a las ${{ env.timestamp }}" > archivo_${{ env.timestamp }}.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: archivo_${{ env.timestamp }}.txt
          path: archivo_${{ env.timestamp }}.txt

  generate-timestamp_v1:
    runs-on: ubuntu-latest
    steps:
      - name: Generate timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%Y%m%d%H%M%S%3NM%S%3N)"

      - name: Set Schema ID
        run: echo "CONNECTIONS_MYCONNECTION_SCHEMA_ID=${{ github.run_id }}_${{ github.run_number }}_${{ steps.timestamp.outputs.timestamp }}" >> $GITHUB_ENV

      - name: Get Schema ID
        run: |
          echo "El Schema ID generado es: ${{ env.CONNECTIONS_MYCONNECTION_SCHEMA_ID }}"
        shell: bash
        working-directory: ${{ github.workspace }}
        env:
          CONNECTIONS_MYCONNECTION_SCHEMA_ID: ${{ env.CONNECTIONS_MYCONNECTION_SCHEMA_ID }}
